# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/99/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/99/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oleg/Public/Oleg/course_2/ded/differentiator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oleg/Public/Oleg/course_2/ded/differentiator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/99/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/clion/98/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/differentiator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named print_latex_referat

# Build rule for target.
print_latex_referat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_latex_referat
.PHONY : print_latex_referat

# fast build rule for target.
print_latex_referat/fast:
	$(MAKE) -f CMakeFiles/print_latex_referat.dir/build.make CMakeFiles/print_latex_referat.dir/build
.PHONY : print_latex_referat/fast

#=============================================================================
# Target rules for targets named count_expression

# Build rule for target.
count_expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 count_expression
.PHONY : count_expression

# fast build rule for target.
count_expression/fast:
	$(MAKE) -f CMakeFiles/count_expression.dir/build.make CMakeFiles/count_expression.dir/build
.PHONY : count_expression/fast

#=============================================================================
# Target rules for targets named read_expression

# Build rule for target.
read_expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_expression
.PHONY : read_expression

# fast build rule for target.
read_expression/fast:
	$(MAKE) -f CMakeFiles/read_expression.dir/build.make CMakeFiles/read_expression.dir/build
.PHONY : read_expression/fast

#=============================================================================
# Target rules for targets named print_tree

# Build rule for target.
print_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_tree
.PHONY : print_tree

# fast build rule for target.
print_tree/fast:
	$(MAKE) -f CMakeFiles/print_tree.dir/build.make CMakeFiles/print_tree.dir/build
.PHONY : print_tree/fast

#=============================================================================
# Target rules for targets named differentiate_tree

# Build rule for target.
differentiate_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 differentiate_tree
.PHONY : differentiate_tree

# fast build rule for target.
differentiate_tree/fast:
	$(MAKE) -f CMakeFiles/differentiate_tree.dir/build.make CMakeFiles/differentiate_tree.dir/build
.PHONY : differentiate_tree/fast

#=============================================================================
# Target rules for targets named print_tree_latex

# Build rule for target.
print_tree_latex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_tree_latex
.PHONY : print_tree_latex

# fast build rule for target.
print_tree_latex/fast:
	$(MAKE) -f CMakeFiles/print_tree_latex.dir/build.make CMakeFiles/print_tree_latex.dir/build
.PHONY : print_tree_latex/fast

#=============================================================================
# Target rules for targets named simplify_tree

# Build rule for target.
simplify_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplify_tree
.PHONY : simplify_tree

# fast build rule for target.
simplify_tree/fast:
	$(MAKE) -f CMakeFiles/simplify_tree.dir/build.make CMakeFiles/simplify_tree.dir/build
.PHONY : simplify_tree/fast

main_files/LaTex_print.o: main_files/LaTex_print.cpp.o

.PHONY : main_files/LaTex_print.o

# target to build an object file
main_files/LaTex_print.cpp.o:
	$(MAKE) -f CMakeFiles/print_tree_latex.dir/build.make CMakeFiles/print_tree_latex.dir/main_files/LaTex_print.cpp.o
.PHONY : main_files/LaTex_print.cpp.o

main_files/LaTex_print.i: main_files/LaTex_print.cpp.i

.PHONY : main_files/LaTex_print.i

# target to preprocess a source file
main_files/LaTex_print.cpp.i:
	$(MAKE) -f CMakeFiles/print_tree_latex.dir/build.make CMakeFiles/print_tree_latex.dir/main_files/LaTex_print.cpp.i
.PHONY : main_files/LaTex_print.cpp.i

main_files/LaTex_print.s: main_files/LaTex_print.cpp.s

.PHONY : main_files/LaTex_print.s

# target to generate assembly for a file
main_files/LaTex_print.cpp.s:
	$(MAKE) -f CMakeFiles/print_tree_latex.dir/build.make CMakeFiles/print_tree_latex.dir/main_files/LaTex_print.cpp.s
.PHONY : main_files/LaTex_print.cpp.s

main_files/count_tree.o: main_files/count_tree.cpp.o

.PHONY : main_files/count_tree.o

# target to build an object file
main_files/count_tree.cpp.o:
	$(MAKE) -f CMakeFiles/count_expression.dir/build.make CMakeFiles/count_expression.dir/main_files/count_tree.cpp.o
.PHONY : main_files/count_tree.cpp.o

main_files/count_tree.i: main_files/count_tree.cpp.i

.PHONY : main_files/count_tree.i

# target to preprocess a source file
main_files/count_tree.cpp.i:
	$(MAKE) -f CMakeFiles/count_expression.dir/build.make CMakeFiles/count_expression.dir/main_files/count_tree.cpp.i
.PHONY : main_files/count_tree.cpp.i

main_files/count_tree.s: main_files/count_tree.cpp.s

.PHONY : main_files/count_tree.s

# target to generate assembly for a file
main_files/count_tree.cpp.s:
	$(MAKE) -f CMakeFiles/count_expression.dir/build.make CMakeFiles/count_expression.dir/main_files/count_tree.cpp.s
.PHONY : main_files/count_tree.cpp.s

main_files/differentiator.o: main_files/differentiator.cpp.o

.PHONY : main_files/differentiator.o

# target to build an object file
main_files/differentiator.cpp.o:
	$(MAKE) -f CMakeFiles/differentiate_tree.dir/build.make CMakeFiles/differentiate_tree.dir/main_files/differentiator.cpp.o
.PHONY : main_files/differentiator.cpp.o

main_files/differentiator.i: main_files/differentiator.cpp.i

.PHONY : main_files/differentiator.i

# target to preprocess a source file
main_files/differentiator.cpp.i:
	$(MAKE) -f CMakeFiles/differentiate_tree.dir/build.make CMakeFiles/differentiate_tree.dir/main_files/differentiator.cpp.i
.PHONY : main_files/differentiator.cpp.i

main_files/differentiator.s: main_files/differentiator.cpp.s

.PHONY : main_files/differentiator.s

# target to generate assembly for a file
main_files/differentiator.cpp.s:
	$(MAKE) -f CMakeFiles/differentiate_tree.dir/build.make CMakeFiles/differentiate_tree.dir/main_files/differentiator.cpp.s
.PHONY : main_files/differentiator.cpp.s

main_files/print_referat.o: main_files/print_referat.cpp.o

.PHONY : main_files/print_referat.o

# target to build an object file
main_files/print_referat.cpp.o:
	$(MAKE) -f CMakeFiles/print_latex_referat.dir/build.make CMakeFiles/print_latex_referat.dir/main_files/print_referat.cpp.o
.PHONY : main_files/print_referat.cpp.o

main_files/print_referat.i: main_files/print_referat.cpp.i

.PHONY : main_files/print_referat.i

# target to preprocess a source file
main_files/print_referat.cpp.i:
	$(MAKE) -f CMakeFiles/print_latex_referat.dir/build.make CMakeFiles/print_latex_referat.dir/main_files/print_referat.cpp.i
.PHONY : main_files/print_referat.cpp.i

main_files/print_referat.s: main_files/print_referat.cpp.s

.PHONY : main_files/print_referat.s

# target to generate assembly for a file
main_files/print_referat.cpp.s:
	$(MAKE) -f CMakeFiles/print_latex_referat.dir/build.make CMakeFiles/print_latex_referat.dir/main_files/print_referat.cpp.s
.PHONY : main_files/print_referat.cpp.s

main_files/print_tree.o: main_files/print_tree.cpp.o

.PHONY : main_files/print_tree.o

# target to build an object file
main_files/print_tree.cpp.o:
	$(MAKE) -f CMakeFiles/print_tree.dir/build.make CMakeFiles/print_tree.dir/main_files/print_tree.cpp.o
.PHONY : main_files/print_tree.cpp.o

main_files/print_tree.i: main_files/print_tree.cpp.i

.PHONY : main_files/print_tree.i

# target to preprocess a source file
main_files/print_tree.cpp.i:
	$(MAKE) -f CMakeFiles/print_tree.dir/build.make CMakeFiles/print_tree.dir/main_files/print_tree.cpp.i
.PHONY : main_files/print_tree.cpp.i

main_files/print_tree.s: main_files/print_tree.cpp.s

.PHONY : main_files/print_tree.s

# target to generate assembly for a file
main_files/print_tree.cpp.s:
	$(MAKE) -f CMakeFiles/print_tree.dir/build.make CMakeFiles/print_tree.dir/main_files/print_tree.cpp.s
.PHONY : main_files/print_tree.cpp.s

main_files/reader.o: main_files/reader.cpp.o

.PHONY : main_files/reader.o

# target to build an object file
main_files/reader.cpp.o:
	$(MAKE) -f CMakeFiles/read_expression.dir/build.make CMakeFiles/read_expression.dir/main_files/reader.cpp.o
.PHONY : main_files/reader.cpp.o

main_files/reader.i: main_files/reader.cpp.i

.PHONY : main_files/reader.i

# target to preprocess a source file
main_files/reader.cpp.i:
	$(MAKE) -f CMakeFiles/read_expression.dir/build.make CMakeFiles/read_expression.dir/main_files/reader.cpp.i
.PHONY : main_files/reader.cpp.i

main_files/reader.s: main_files/reader.cpp.s

.PHONY : main_files/reader.s

# target to generate assembly for a file
main_files/reader.cpp.s:
	$(MAKE) -f CMakeFiles/read_expression.dir/build.make CMakeFiles/read_expression.dir/main_files/reader.cpp.s
.PHONY : main_files/reader.cpp.s

main_files/simplifier.o: main_files/simplifier.cpp.o

.PHONY : main_files/simplifier.o

# target to build an object file
main_files/simplifier.cpp.o:
	$(MAKE) -f CMakeFiles/simplify_tree.dir/build.make CMakeFiles/simplify_tree.dir/main_files/simplifier.cpp.o
.PHONY : main_files/simplifier.cpp.o

main_files/simplifier.i: main_files/simplifier.cpp.i

.PHONY : main_files/simplifier.i

# target to preprocess a source file
main_files/simplifier.cpp.i:
	$(MAKE) -f CMakeFiles/simplify_tree.dir/build.make CMakeFiles/simplify_tree.dir/main_files/simplifier.cpp.i
.PHONY : main_files/simplifier.cpp.i

main_files/simplifier.s: main_files/simplifier.cpp.s

.PHONY : main_files/simplifier.s

# target to generate assembly for a file
main_files/simplifier.cpp.s:
	$(MAKE) -f CMakeFiles/simplify_tree.dir/build.make CMakeFiles/simplify_tree.dir/main_files/simplifier.cpp.s
.PHONY : main_files/simplifier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... print_latex_referat"
	@echo "... count_expression"
	@echo "... read_expression"
	@echo "... print_tree"
	@echo "... differentiate_tree"
	@echo "... print_tree_latex"
	@echo "... simplify_tree"
	@echo "... main_files/LaTex_print.o"
	@echo "... main_files/LaTex_print.i"
	@echo "... main_files/LaTex_print.s"
	@echo "... main_files/count_tree.o"
	@echo "... main_files/count_tree.i"
	@echo "... main_files/count_tree.s"
	@echo "... main_files/differentiator.o"
	@echo "... main_files/differentiator.i"
	@echo "... main_files/differentiator.s"
	@echo "... main_files/print_referat.o"
	@echo "... main_files/print_referat.i"
	@echo "... main_files/print_referat.s"
	@echo "... main_files/print_tree.o"
	@echo "... main_files/print_tree.i"
	@echo "... main_files/print_tree.s"
	@echo "... main_files/reader.o"
	@echo "... main_files/reader.i"
	@echo "... main_files/reader.s"
	@echo "... main_files/simplifier.o"
	@echo "... main_files/simplifier.i"
	@echo "... main_files/simplifier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

